var imglib = [
{
	"sheetname"				: "playersheet",
	"type"					: "player",
	"src"					: "library/playersheet.png",
	"width"					: 96,
	"height"				: 32,
	"framewidth"			: 32,
	"frameheight"			: 32,
	"framedelay"			: 4,
	"framesperdirection"	: 2,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
},
{
	"sheetname"				: "explosionsheet",
	"type"					: "explosion",
	"src"					: "library/explosion.png",
	"width"					: 192,
	"height"				: 32,
	"framewidth"			: 32,
	"frameheight"			: 32,
	"framedelay"			: 1,
	"framesperdirection"	: 5,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
},
{
	"sheetname"				: "aliensheet",
	"type"					: "alien",
	"src"					: "library/aliensheet.png",
	"width"					: 48,
	"height"				: 96,
	"framewidth"			: 24,
	"frameheight"			: 24,
	"framedelay"			: 4,
	"framesperdirection"	: 2,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
},
{
	"sheetname"				: "alienbombsheet",
	"type"					: "alienbomb",
	"src"					: "library/alienbomb.png",
	"width"					: 64,
	"height"				: 32,
	"framewidth"			: 16,
	"frameheight"			: 16,
	"framedelay"			: 2,
	"framesperdirection"	: 4,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
},
{
	"sheetname"				: "laserssheet",
	"type"					: "laser",
	"src"					: "library/lasers.gif",
	"width"					: 4,
	"height"				: 16,
	"framewidth"			: 4,
	"frameheight"			: 16,
	"framedelay"			: 0,
	"framesperdirection"	: 1,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
},
{
	"sheetname"				: "bonussheet",
	"type"					: "bonus",
	"src"					: "library/bonusitems.gif",
	"width"					: 64,
	"height"				: 128,
	"framewidth"			: 32,
	"frameheight"			: 32,
	"framedelay"			: 4,
	"framesperdirection"	: 2,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
}
];