var res = {
		android_bj : "res/android_bj.png",
		game_bj : "res/game_bj.png",
		banquan : "res/banquan.png",
		menu_door_1 : "res/menu_door_1.png",
		menu_door_2 : "res/menu_door_2.png",
		menubutton1 : "res/menubutton1.png",
		menubutton2 : "res/menubutton2.png",
		shadow1 : "res/shadow1.png",
		background_suc20001 : "res/background_suc20001.png",
		background_suc20002 : "res/background_suc20002.png",
		photo_1 : "res/photo_1.png",
		photo_2 : "res/photo_2.png",
		photo_3 : "res/photo_3.png",
		photo_4 : "res/photo_4.png",
		photo_5 : "res/photo_5.png",
		photo_6 : "res/photo_6.png",
		photo_7 : "res/photo_7.png",
		photo_fail : "res/photo_fail.png",
		new_mini : "res/new_mini.png",
		moregames : "res/moregames.png",
		orangebutton : "res/orangebutton.png",
		blackboard : "res/blackboard.png",
		bluebutton : "res/bluebutton.png",
		bluebutton2 : "res/bluebutton2.png",
		game_door1_close : "res/game_door1_close.png",
		game_door2_open1 : "res/game_door2_open1.png",
		game_door2_open2 : "res/game_door2_open2.png",
		game_door2_open3 : "res/game_door2_open3.png",
		game_door2_open4 : "res/game_door2_open4.png",
		lock1 : "res/lock1.png",
		lock2 : "res/lock2.png",
		lock3 : "res/lock3.png",
		lock4 : "res/lock4.png",
		new_mini : "res/new_mini.png",
		newscore : "res/newscore.png",
		replaymini : "res/replaymini.png",
		shadowbig : "res/shadowbig.png",
		tongyong_back : "res/tongyong_back.png",
		tongyong_help : "res/tongyong_help.png",
		jiantou : "res/jiantou.png",
		shou : "res/shou1.png",
		yuan : "res/yuan1.png",
		help1 : "res/help1.png",
		help2 : "res/help2.png",
		share : "res/share.png",
		//error : "res/error.wav",
		//sound_1 : "res/sound_1.wav",
		//sound_2 : "res/sound_2.wav",
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}