var imglib = [
{
	"sheetname"				: "playersheet",
	"type"					: "player",
	"src"					: "library/playersheet.gif",
	"width"					: 264,
	"height"				: 64,
	"framewidth"			: 24,
	"frameheight"			: 32,
	"framedelay"			: 2,
	"framesperdirection"	: 10,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
},
{
	"sheetname"				: "jumppad",
	"type"					: "jumppad",
	"src"					: "library/jumppad.gif",
	"width"					: 128,
	"height"				: 32,
	"framewidth"			: 32,
	"frameheight"			: 32,
	"framedelay"			: 8,
	"framesperdirection"	: 4,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
},
{
	"sheetname"				: "keyssheet",
	"type"					: "keys",
	"src"					: "library/keyssheet.gif",
	"width"					: 32,
	"height"				: 16,
	"framewidth"			: 16,
	"frameheight"			: 16,
	"framedelay"			: 2,
	"framesperdirection"	: 2,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
},
{
	"sheetname"				: "explosionsheet",
	"type"					: "explosion",
	"src"					: "library/explosion.png",
	"width"					: 192,
	"height"				: 32,
	"framewidth"			: 32,
	"frameheight"			: 32,
	"framedelay"			: 1,
	"framesperdirection"	: 5,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
},
{
	"sheetname"				: "aliensheet",
	"type"					: "alien",
	"src"					: "library/aliensheet.gif",
	"width"					: 48,
	"height"				: 120,
	"framewidth"			: 24,
	"frameheight"			: 24,
	"framedelay"			: 4,
	"framesperdirection"	: 2,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
},
{
	"sheetname"				: "fireswirl",
	"type"					: "fireswirl",
	"src"					: "library/fireswirl.gif",
	"width"					: 48,
	"height"				: 48,
	"framewidth"			: 24,
	"frameheight"			: 24,
	"framedelay"			: 4,
	"framesperdirection"	: 2,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
},
{
	"sheetname"				: "alienbombsheet",
	"type"					: "alienbomb",
	"src"					: "library/alienbomb.png",
	"width"					: 64,
	"height"				: 32,
	"framewidth"			: 16,
	"frameheight"			: 16,
	"framedelay"			: 2,
	"framesperdirection"	: 4,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
},
{
	"sheetname"				: "platformsheet",
	"type"					: "platform",
	"src"					: "library/platforms.gif",
	"width"					: 128,
	"height"				: 80,
	"framewidth"			: 16,
	"frameheight"			: 16,
	"framedelay"			: 2,
	"framesperdirection"	: 0,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
}
];
