var imglib = [
{
	"sheetname"				: "playersheet",
	"type"					: "player",
	"src"					: "library/dragon.gif",
	"width"					: 352,
	"height"				: 64,
	"framewidth"			: 32,
	"frameheight"			: 32,
	"framedelay"			: 3,
	"framesperdirection"	: 3,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 8,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
},
{
	"sheetname"				: "monstersheet",
	"type"					: "monster",
	"src"					: "library/monstersheet.gif",
	"width"					: 160,
	"height"				: 64,
	"framewidth"			: 32,
	"frameheight"			: 32,
	"framedelay"			: 8,
	"framesperdirection"	: 2,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
},
{
	"sheetname"				: "bombsheet",
	"type"					: "bomb",
	"src"					: "library/bombs.gif",
	"width"					: 32,
	"height"				: 32,
	"framewidth"			: 32,
	"frameheight"			: 32,
	"framedelay"			: 2,
	"framesperdirection"	: 1,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
},
{
	"sheetname"				: "itemsheet",
	"type"					: "item",
	"src"					: "library/itemsheet.gif",
	"width"					: 48,
	"height"				: 128,
	"framewidth"			: 24,
	"frameheight"			: 32,
	"framedelay"			: 4,
	"framesperdirection"	: 2,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
},
{
	"sheetname"				: "bonussheet",
	"type"					: "bonus",
	"src"					: "library/bonussheet.gif",
	"width"					: 32,
	"height"				: 48,
	"framewidth"			: 16,
	"frameheight"			: 16,
	"framedelay"			: 4,
	"framesperdirection"	: 2,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
}
];